FROM debian:bookworm-slim

RUN apt update && apt install -y --no-install-recommends \
	ca-certificates curl git cmake make g++ libncurses-dev xz-utils \
	gdbserver libcurl4-openssl-dev

# grab and extract a frida-gadget
ENV FRIDA_VERSION=16.1.8
RUN cd /usr/lib && \
	curl -O -fsSL https://github.com/frida/frida/releases/download/${FRIDA_VERSION}/frida-gadget-${FRIDA_VERSION}-linux-x86_64.so.xz && \
	unxz frida-gadget-${FRIDA_VERSION}-linux-x86_64.so.xz && \
	mv frida-gadget-${FRIDA_VERSION}-linux-x86_64.so libgadget.so
COPY frida/frida-gadget.config /usr/lib/libgadget.config

# orig: https://github.com/Holixus/tty-tetris-v2.git
ADD tty-tetris-v2/ /usr/src/tty-tetris-v2/
RUN cd /usr/src/tty-tetris-v2 && \
	cmake . && \
	make && \
	cp tty-tetris /usr/local/bin/tetris

# shared flag lib
ADD libttyris/ /usr/src/libttyris/
RUN cd /usr/src/libttyris && \
	cmake . && \
	make && \
	cp libttyris.so /usr/lib

RUN alias tetris-debug="gdbserver :1234 tetris"

CMD [ "bash" ]
