FROM debian:bookworm-slim

RUN apt update && apt install -y --no-install-recommends \
	ca-certificates curl git cmake make g++ libncurses-dev xz-utils \
	gdbserver

# build https://github.com/k-vernooy/tetris
# build https://github.com/Holixus/tty-tetris-v2.git
ADD tty-tetris-v2/ /usr/src/tty-tetris-v2/
RUN cd /usr/src/tty-tetris-v2 && \
	cmake . && \
	make && \ 
	ls -lah

# grab and extract a frida-gadget
ENV FRIDA_VERSION=16.1.8
RUN cd /usr/local/lib/ && \
	curl -O -fsSL https://github.com/frida/frida/releases/download/${FRIDA_VERSION}/frida-gadget-${FRIDA_VERSION}-linux-x86_64.so.xz && \
	unxz frida-gadget-${FRIDA_VERSION}-linux-x86_64.so.xz && \
	mv frida-gadget-${FRIDA_VERSION}-linux-x86_64.so libgadget.so
COPY frida/frida-gadget.config /usr/local/lib/libgadget.config

WORKDIR /usr/src/tty-tetris-v2

CMD [ "bash" ]
