FROM debian:bookworm-slim

RUN apt update && apt install -y --no-install-recommends \
	ca-certificates curl git cmake make g++ libncurses-dev xz-utils

# build https://github.com/k-vernooy/tetris
# build https://github.com/Holixus/tty-tetris-v2.git
ADD tty-tetris-v2/ /usr/src/tty-tetris-v2/
RUN cd /usr/src/tty-tetris-v2 && \
	cmake . && \
	make && \ 
	ls -lah

CMD [ "bash" ]
