# the port that ssh connections should be accepted on
# to start the challenge
container_ssh_port: 24

# the name of the challenge container that will be spawned
# when a new ssh connection comes in
chal_container_name: frown:local

# name of the flag http server container that will live
# in the background
flag_service_container_name: frown-flag:local

# name challenge relevant docker containers will connect to
docker_network_name: frownnet

# by default we force users to auth using a github/gitlab key.
# setting this to true will remove that restriction making it
# possible to authenticate as the "user" with a configured pass.
local_auth: true
local_auth_password: 1nsomn1h4cker
