- name: setup the frown challenge
  hosts: all
  become: yes
  roles:
    # a sane way to get docker installed and configured
    - geerlingguy.docker
  tasks:
    # systemd socket activation configuration
    # idea originally from: https://ecksun.com/systemd/2016/08/13/Socket_activated_containers.html
    - name: copy over systemd container ssh socket file
      template:
        src: cssh.socket.j2
        dest: /usr/lib/systemd/system/cssh.socket
    - name: copy over systemd container ssh service file
      template:
        src: cssh@.service.j2
        dest: /usr/lib/systemd/system/cssh@.service
    - name: enable the cssh.socket service
      ansible.builtin.systemd_service:
        enabled: true
        state: started
        name: cssh.socket

    # prepare and build the docker container spawned via socket activation
    - name: copy docker container artefacts to host
      ansible.builtin.copy:
        mode: preserve
        src: docker-challenge/
        dest: /root/docker-challenge
    - name: build challenge docker container
      community.docker.docker_image:
        name: '{{ container_name }}'
        build:
          path: /root/docker-challenge
        source: build
    - name: cleanup docker container artefacts after container build
      ansible.builtin.file:
        state: absent
        path: /root/docker-challenge
